### ISSUE TITLE
Provide documentation for code 

### ISSUE THREAD

**Issue by ksgr5566** [facebookresearch/NASViT#6]
Hello, 
I have been following the work related to using NAS for Vision Transformers. I am reading your approach from the NASViT paper, it would be very helpful if you could provide a documentation for your module and add descriptive comments in the code.

**Comment by ChengyueGongR** [comment]
Hi, thanks for your advice. We do not plan to write a document now, and we refer the users to the [AttentiveNAS](https://github.com/facebookresearch/AttentiveNAS) to see the usage.
