### ISSUE TITLE
Porblems with calculating flops

### ISSUE THREAD

**Issue by dixiyao** [facebookresearch/NASViT#7]
Hi, when I want to use the function
```
compute_active_subnet_flops() 
``` 
in the model class
```
attentive_nas_dynamic_model.py
```
It will output an error said that NoneType has no active_expand_ratio. I guess the problem is this is desgined for mb and I did not find the logic of logging flops of transformer block.

**Comment by ChengyueGongR** [comment]
Hi, thanks for your interest. This function only gives the flops for conv layers. We do not use the function compute_active_subnet_flops() to calculate the FLOPs for attention layers. Instead, we calculate the transformer layer cost separately and add the attention layer cost and the result of compute_active_subnet_flops() together.
